default_install_hook_types: [commit-msg, pre-commit]
repos:
    - repo: local
      hooks:
        - id: commitizen
          name: commitizen check
          language: python
          stages: [commit-msg]
          description: "Check whether commit message follows commiting rules"
          entry: cz check --commit-msg-file

        - id: ruff
          name: ruff
          language: python
          stages: [pre-commit]
          entry: ruff check
          args: [ --fix ]
          files: |
            (?x)(
            \.(py)$
            )

        - id: ruff-formatter
          name: ruff-formatter
          language: python
          stages: [pre-commit]
          entry: ruff formatter
          files: |
            (?x)(
            \.(py)$
            )

        - id: pylint
          name: pylint
          language: python
          stages: [pre-commit]
          entry: pylint
          files: |
            (?x)(
            \.(py)$
            )

        - id: xenon
          name: xenon
          language: python
          stages: [pre-commit]
          entry: xenon
          args: ["--max-absolute=A", "--max-modules=A", "--max-average=A"]
          files: |
            (?x)(
            \.(py)$
            )