apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
commonLabels:
    app.kubernetes.io/name: my-package
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: data-analytics 
    env: staging
labels:
    - includeSelectors: false
      includeTemplates: true
      pairs:
        app.kubernetes.io/version: $VERSION
resources:
    - deployment.yaml
    - ingress.yaml
    - pvc.yaml
    - service.yaml
    - configmap.yaml
    